name: CI Build Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: |
            3.12
            3.11
            3.10
            3.9

      - name: Install dependencies
        run: |
          python -m venv venv
          .\venv\Scripts\activate
          pip install -r requirements.txt

      - name: Run build
        run: |
          .\venv\Scripts\activate
          .\build.bat

      - name: Clean up
        run: |
          echo Cleaning up...
          rmdir /s /q venv
